import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'

import Image from 'app/components/atoms/Image'
import styles from './HomePage.module.css'

const HomePage: NextPage = () => (
  <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
      <h1 className={styles.title}>
        Welcome to <a href="https://nextjs.org">Next.js!</a>
      </h1>

      <p className={styles.description}>
        Get started by editing{' '}
        <code className={styles.code}>app/views/HomePage/HomePage.tsx</code>
      </p>
      <div className={styles.footer}>
        <Image alt="Next.js" src="/nextjs.png" width={80} height={48} />
      </div>
    </main>
  </div>
)

export default HomePage
